server:
  port: 8081

spring:
  application:
    name: scrapper

app:
  clients:
    bot-base-url: ${BOT_BASE_URL}
  stackoverflow:
    base-url: ${STACKOVERFLOW_BASE_URL}
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
  github:
    base-url: ${GITHUB_BASE_URL}
    token: ${GITHUB_TOKEN}
  polling:
    interval: 60s
