server:
  port: 8080

spring:
  application:
    name: bot

app:
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN} # Use env variable. DO NOT KEEP TOKEN HERE
    update-listener-sleep: 1s
    debug: false
  scrapper:
    base-url: http://localhost:8081
  messages:
    unknown-command: "Неизвестная команда. Воспользуйтесь /help, чтобы посмотреть список доступных команд."
    start-welcome: "Ку, %s! Используйте /help, чтобы посмотреть доступные команды."
    welcome-back: "С возвращением, %s! Используйте /help, чтобы посмотреть доступные команды."
    help-header: "Доступные команды:"
    track-started: "Пришлите ссылку, которую хотите отслеживать."
    track-ask-tags: "Теперь пришлите теги через запятую или отправьте '-' если теги не нужны."
    track-cancelled: "Отслеживание ссылки отменено."
    nothing-to-cancel: "Сейчас нечего отменять."
    invalid-link: "Некорректная ссылка."
    already-tracked: "Ссылка уже отслеживается"
    link-tracked: "Ссылка добавлена в отслеживание."
    link-removed: "Ссылка удалена из отслеживания."
    link-not-found: "Ссылка не найдена."
    no-tracked-links: "У вас нет отслеживаемых ссылок."
    chat-not-registered: "Сначала используйте /start."
    untrack-usage: "Использование: /untrack <ссылка>"
    scrapper-unavailable: "Сервис отслеживания сейчас недоступен. Попробуйте позже."
    updates-template: |
      Обнаружено обновление по ссылке: %s
      %s
